name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v4
      - uses: actions/setup-node@32f57ac043e003bc1b07edcb2b9102bbbf3e92f1 # v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run build
      - uses: SonarSource/sonarcloud-github-action@ba3875ecf642b2129de2b589510c81a8b53dbf4e # v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
